"""Application layer: the verifiable circular olive-oil passport.

Document: "a digital record that explains where the oil came from, how it was
processed, how its quality was assessed, what residues were produced, how
those residues were valorized, and which actors earned rewards for verified
sustainable actions." Consumer-facing: "credible, understandable evidence —
not technical blockchain terminology without context."
"""
from __future__ import annotations

from .evidence import EvidenceStore
from .ledger import Ledger
from .massbalance import reconcile_residue
from .models import EventType

LOOP1_ORDER = [
    EventType.CULTIVATION, EventType.HARVEST, EventType.COLLECTION_TRANSPORT,
    EventType.MILLING, EventType.LAB_VERIFICATION, EventType.BOTTLING,
    EventType.DISTRIBUTION_RETAIL,
]

STAGE_LABELS = {
    EventType.CULTIVATION.value: "Grown",
    EventType.HARVEST.value: "Harvested",
    EventType.COLLECTION_TRANSPORT.value: "Collected",
    EventType.MILLING.value: "Milled",
    EventType.LAB_VERIFICATION.value: "Quality verified",
    EventType.BOTTLING.value: "Bottled",
    EventType.DISTRIBUTION_RETAIL.value: "Shipped to market",
}


def build_passport(ledger: Ledger, batch_id: str, evidence_store: EvidenceStore | None = None) -> dict:
    """Assemble the batch passport. Verification is real: the hash chain and
    signatures are re-checked at assembly time, and each off-chain evidence
    file is re-hashed against its on-chain anchor."""
    chain_ok, chain_problems = ledger.verify_chain()

    # include superseded originals: corrections supersede, they don't erase —
    # the stage still happened and is shown with its corrected values
    batch_events = ledger.for_subject(batch_id, include_superseded=True)
    stages = []
    residue_ids: list[str] = []
    for ev in sorted(batch_events, key=lambda e: e.timestamp):
        if ev.event_type not in STAGE_LABELS:
            continue
        p = ledger.effective_payload(ev)
        org = ledger.registry.get(ev.actor_org)
        evidence_status = []
        for ref in ev.evidence:
            ok = evidence_store.verify(ref) if evidence_store else None
            evidence_status.append({"name": ref["name"], "sha256": ref["sha256"], "intact": ok})
        if ev.event_type == EventType.MILLING.value:
            for r in p.get("residues_declared", []):
                if r.get("residue_id"):
                    residue_ids.append(r["residue_id"])
        stages.append({
            "stage": STAGE_LABELS[ev.event_type],
            "event_type": ev.event_type,
            "by": org.name,
            "org_roles": [r.value for r in org.roles],
            "timestamp": ev.timestamp,
            "details": p,
            "evidence": evidence_status,
            "signed": True,
            "corrected": ev.payload != p,
        })

    # Loop 2: circular story per residue lot generated by this batch
    circular = []
    for rid in residue_ids:
        rec = reconcile_residue(ledger, rid)
        gen = next((e for e in ledger.for_subject(rid)
                    if e.event_type == EventType.RESIDUE_GENERATION.value), None)
        circular.append({
            "residue_id": rid,
            "residue_type": ledger.effective_payload(gen).get("residue_type") if gen else None,
            "generated_kg": rec.generated_kg,
            "recovered_outputs": rec.outputs,
            "recovery_pct": rec.recovery_pct,
            "mass_balance_ok": rec.balanced,
            "issues": rec.issues,
        })

    # Rewards earned by actors on this batch's events
    basis_ids = {e.event_id for e in batch_events} | {
        e.event_id for rid in residue_ids for e in ledger.for_subject(rid)
    }
    rewards = []
    for ev in ledger.iter_type(EventType.REWARD_ISSUED):
        if set(ev.payload["basis_events"]) & basis_ids:
            rewards.append({
                "recipient": ledger.registry.get(ev.payload["recipient"]).name,
                "amount": ev.payload["amount"],
                "for": ev.payload["reward_rule"],
            })

    # Wallet-native rewards (OliveToken, EcoToken and TrustScore changes).
    wallet_rewards = []
    token_query = getattr(ledger, "token_transactions_for_subject", None)
    if callable(token_query):
        try:
            seen = set()
            for tx in token_query(batch_id):
                tx_id = tx.get("token_tx_id", "")
                if tx_id and tx_id in seen:
                    continue
                if tx_id:
                    seen.add(tx_id)
                wallet_rewards.append(tx)
        except Exception:
            wallet_rewards = []

    scans = sum(1 for e in ledger.iter_type(EventType.CONSUMER_VERIFICATION)
                if e.subject_id == batch_id)

    return {
        "batch_id": batch_id,
        "ledger_verified": chain_ok,
        "ledger_problems": chain_problems,
        "stages": stages,
        "circular": circular,
        "rewards": rewards,
        "wallet_rewards": wallet_rewards,
        "consumer_scans": scans,
    }
