name: olivechain-machine4-ca

services:
  ca_peer:
    image: hyperledger/fabric-ca:${FABRIC_CA_VERSION}
    container_name: ca.recycler.olivechain.local
    hostname: ca.recycler.olivechain.local
    restart: unless-stopped
    environment:
      FABRIC_CA_HOME: /etc/hyperledger/fabric-ca-server
      FABRIC_CA_SERVER_CA_NAME: ca-recycler
      FABRIC_CA_SERVER_TLS_ENABLED: "true"
      FABRIC_CA_SERVER_CSR_HOSTS: ca.recycler.olivechain.local,${MACHINE_FQDN},localhost,${MACHINE_IP}
    command: sh -c 'fabric-ca-server start -b admin:${CA_ADMIN_PASSWORD} -d'
    ports:
      - "127.0.0.1:7054:7054"
    volumes:
      - ../../runtime/machine4/ca/recycler:/etc/hyperledger/fabric-ca-server
    networks:
      - olivechain

networks:
  olivechain:
    name: olivechain-machine4
